### ISSUE TITLE
🔧 ✍️ Add local emulators and document how to run the system

### ISSUE THREAD

**Issue by jrosseel** [italanta/kujali#27]
As a developer, I need to be able to install and run the system so that I have a basis from which to contribute to the project.

### Tasks

- [x] Install local emulators for firebase
- [x] Install local emulator (Docker) for SQL database
- [x] Add dynamic configuration that runs and uses the local emulators through the command "npm run run-develop"
- [x] Document installation procedure for new developers, including:
   - [x] Installation for Windows and Mac (packages to install (node, firebase, docker, ...)
   - [x] Running npm install
   - [x] Creating a firebase project & adding firebase environment (if necessary [ref. emulators -> could they do everything])
   - [x] Running the project

- [x] Create data seeds (so local emulators have initial data such as demo user and dummy data) [lower priority]
- [x] Seed data on emulator launch

### Acceptance criteria

- [ ] As a developer, I can install Kujali and run it on my local machine without external help (using only the readme.md)
